main: me.Midnight.StaffDuty.StaffDuty
name: StaffDuty
version: '1.1'
description: Toggle staff rank
author: MidnightCore
website: spigotmc.org
depend:
  - PlaceholderAPI
commands:
  toggleduty:
    description: Toggle your dutty
    usage: /<command>
    permission: toggleduty.staff